export interface ICar {
    "price": number,
    "image": any,
    "name": string,
    "cylinder": number,
    "fuel": number,
    "transmission": number,
    "description": string,
    "model": string,
    "body": string,
    "volume": string,
    "mileage": string,
    "doors": string,
    "phone_number": string,
    id?: string,
    year?: string,
    production? :string,
    code?: string,
}
