export const cars = [
    {
        title: 'Mersedes-Benz',
        description: 'This is a car',
        year: '2022',
        production: 'Abu-Dhabi',
        price: '48',
        mileage: '39,433',
        id: 1,
        preview: 'https://www.avtovzglyad.ru/media/article/sha.jpg.740x555_q85_box-0%2C0%2C1024%2C768_crop_detail_upscale.jpg',
        code: 'AED',
    },
    {
        title: 'KIA Sport',
        description: '',
        year: '2022',
        production: 'Japan',
        price: '100',
        mileage: '45,433',
        id: 2,
        preview: 'https://masllo.com/wp-content/uploads/2021/05/kia.jpg',
        code: 'JPN',
    },
    {
        title: 'Mersedes-Benz',
        description: 'This is Mersedes',
        year: '2022',
        production: 'Abu-Dhabi',
        price: '120',
        mileage: '3,433',
        id: 3,
        preview: 'https://www.autostrada.uz/wp-content/uploads/2018/03/1280px-Mercedes_C_200_Kompressor_Elegance_W204_front_20100425.jpg',
        code: 'AED',
    },
    {
        title: 'Mersedes-Benz',
        description: 'Mersedes-Benz Description',
        year: '2022',
        production: 'Abu-Dhabi',
        price: '150',
        mileage: '5,433',
        id: 4,
        preview: 'https://cdn.riastatic.com/photosnewr/auto/new_auto_storage/mercedes-benz-s-class__1070352-620x465x70.jpg',
        code: 'AED',
    },
    {
        title: 'Mersedes-Benz',
        description: 'Mersedes-Benz',
        year: '2021',
        production: 'Abu-Dhabi',
        price: '67',
        mileage: '39,433',
        id: 5,
        preview: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTDcssFpN5vKLVdglznpV4Qq4n6UbTYC8LxQ&usqp=CAU',
        code: 'AED',
    },
    {
        title: 'Audi',
        description: 'This is Audi',
        year: '2021',
        production: 'Abu-Dhabi',
        price: '160',
        mileage: '55,433',
        id: 6,
        preview: 'https://avatars.mds.yandex.net/get-zen_doc/1584893/pub_5f9156e22c1a69338e810185_5f915ee62c1a69338e8efd29/scale_1200',
        code: 'ADE',
    },
    {
        title: 'Audi',
        description: 'Audi',
        year: '2020',
        production: 'Abu-Dhabi',
        price: '170',
        mileage: '39,433',
        id: 7,
        preview: 'https://avatars.mds.yandex.net/get-zen_doc/3986532/pub_5f9156e22c1a69338e810185_5f915f212c1a69338e8f6747/scale_1200',
        code: 'AED',
    },
    {
        title: 'Honda',
        description: 'Honda',
        year: '2022',
        production: 'New-York',
        price: '89',
        mileage: '1',
        id: 8,
        preview: 'https://leasing.express/wp-content/themes/leasinge/assets/images/sold/220222/Accord.jpg',
        code: 'New-York',
    },
    {
        title: 'Lexus',
        description: 'This is a car Lexus',
        year: '2020',
        production: 'Abu-Dhabi',
        price: '200',
        mileage: '39,433',
        id: 9,
        preview: 'https://avatars.mds.yandex.net/get-autoru-vos/1676748/25be70972fa959ac843e2238113c83bc/456x342n',
        code: 'AED',
    },
    {
        title: 'Audi',
        description: 'This is a car Audi',
        year: '2020',
        production: 'Germany',
        price: '120',
        mileage: '5,433',
        id: 10,
        preview: 'https://avto-flot.ru/img/blog/AudiQ8NewTest1.jpg',
        code: 'GRM',
    },
    {
        title: 'Lexus',
        description: 'This is a car Lexus',
        year: '2020',
        production: 'Abu-Dhabi',
        price: '200',
        mileage: '39,433',
        id: 11,
        preview: 'https://avatars.mds.yandex.net/get-autoru-vos/1956707/1183bfe8b83f93dc73724bf1ad6a1c96/456x342n',
        code: 'AED',
    },
    {
        title: 'Honda',
        description: 'Honda',
        year: '2019',
        production: 'New-York',
        price: '100',
        mileage: '5',
        id: 12,
        preview: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyHarV7LjKQXdeYvPa0TvdCw0RlPFmFifpUQ&usqp=CAU',
        code: 'New-York',
    },
]

export const spare = [
    {
        title: 'Профит Генератор',
        description: 'Профит Генератор нужен каждому авто...',
        year: '2022',
        production: 'Japan',
        price: '100',
        mileage: '39,433',
        id: 1,
        preview: 'https://i.avto.pro/img/mi/55054/67/01.jpeg',
        code: 'AED',
    },
    {
        title: 'Генератор Mitsubishi-Lancer',
        description: 'Генератор Mitsubishi-Lancer',
        year: '2015',
        production: 'Japan',
        price: '150',
        mileage: '39,433',
        id: 2,
        preview: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8fQ65HdKp4rcFkkgBRl4iLUTh66gczL5pBxO7Z-UnuFrm_PW5RMZP4jxzSMGHki3k_s4&usqp=CAU',
        code: 'JPN',
    },
    {
        title: 'Тормозные колодки',
        description: 'Если у вас колодки пришли в непригодное состояние то...',
        year: '2020',
        production: 'Korea',
        price: '50',
        mileage: '0',
        id: 3,
        preview: 'https://image.made-in-china.com/43f34j00KPAfIEwJntbg/Brake-Shoe-Auto-Spare-Parts-Accessories-Car-Parts-for-Byd-10136441-00-.jpg',
        code: 'KOR',
    },
    {
        title: 'Светодионовые фары',
        description: 'Светодионовые фары',
        year: '2022',
        production: 'China',
        price: '100',
        mileage: '39,433',
        id: 4,
        preview: 'https://content1.rozetka.com.ua/goods/images/big/34476177.jpg',
        code: 'CHN',
    },
    {
        title: 'Светодионовые фары',
        description: 'Светодионовые фары',
        year: '2022',
        production: 'China',
        price: '100',
        mileage: '39,433',
        id: 4,
        preview: 'https://content1.rozetka.com.ua/goods/images/big/34476177.jpg',
        code: 'CHN',
    },
    {
        title: 'Тормозные колодки',
        description: 'Если у вас колодки пришли в непригодное состояние то...',
        year: '2020',
        production: 'Korea',
        price: '50',
        mileage: '0',
        id: 3,
        preview: 'https://image.made-in-china.com/43f34j00KPAfIEwJntbg/Brake-Shoe-Auto-Spare-Parts-Accessories-Car-Parts-for-Byd-10136441-00-.jpg',
        code: 'KOR',
    },
    {
        title: 'Профит Генератор',
        description: 'Профит Генератор нужен каждому авто...',
        year: '2022',
        production: 'Japan',
        price: '100',
        mileage: '39,433',
        id: 1,
        preview: 'https://i.avto.pro/img/mi/55054/67/01.jpeg',
        code: 'AED',
    },
    {
        title: 'Генератор Mitsubishi-Lancer',
        description: 'Генератор Mitsubishi-Lancer',
        year: '2015',
        production: 'Japan',
        price: '150',
        mileage: '39,433',
        id: 2,
        preview: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8fQ65HdKp4rcFkkgBRl4iLUTh66gczL5pBxO7Z-UnuFrm_PW5RMZP4jxzSMGHki3k_s4&usqp=CAU',
        code: 'JPN',
    },
]

