
export const spare = [
    {
        title: 'Профит Генератор',
        description: 'Профит Генератор нужен каждому авто...',
        year: '2022',
        production: 'Japan',
        price: '100',
        mileage: '39,433',
        id: 1,
        image: 'https://i.avto.pro/img/mi/55054/67/01.jpeg',
        code: 'AED',
    },
    {
        title: 'Генератор Mitsubishi-Lancer',
        description: 'Генератор Mitsubishi-Lancer',
        year: '2015',
        production: 'Japan',
        price: '150',
        mileage: '39,433',
        id: 2,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8fQ65HdKp4rcFkkgBRl4iLUTh66gczL5pBxO7Z-UnuFrm_PW5RMZP4jxzSMGHki3k_s4&usqp=CAU',
        code: 'JPN',
    },
    {
        title: 'Тормозные колодки',
        description: 'Если у вас колодки пришли в непригодное состояние то...',
        year: '2020',
        production: 'Korea',
        price: '50',
        mileage: '0',
        id: 3,
        image: 'https://image.made-in-china.com/43f34j00KPAfIEwJntbg/Brake-Shoe-Auto-Spare-Parts-Accessories-Car-Parts-for-Byd-10136441-00-.jpg',
        code: 'KOR',
    },
    {
        title: 'Светодионовые фары',
        description: 'Светодионовые фары',
        year: '2022',
        production: 'China',
        price: '100',
        mileage: '39,433',
        id: 4,
        image: 'https://content1.rozetka.com.ua/goods/images/big/34476177.jpg',
        code: 'CHN',
    },
    {
        title: 'Светодионовые фары',
        description: 'Светодионовые фары',
        year: '2022',
        production: 'China',
        price: '100',
        mileage: '39,433',
        id: 4,
        image: 'https://content1.rozetka.com.ua/goods/images/big/34476177.jpg',
        code: 'CHN',
    },
    {
        title: 'Тормозные колодки',
        description: 'Если у вас колодки пришли в непригодное состояние то...',
        year: '2020',
        production: 'Korea',
        price: '50',
        mileage: '0',
        id: 3,
        image: 'https://image.made-in-china.com/43f34j00KPAfIEwJntbg/Brake-Shoe-Auto-Spare-Parts-Accessories-Car-Parts-for-Byd-10136441-00-.jpg',
        code: 'KOR',
    },
    {
        title: 'Профит Генератор',
        description: 'Профит Генератор нужен каждому авто...',
        year: '2022',
        production: 'Japan',
        price: '100',
        mileage: '39,433',
        id: 1,
        image: 'https://i.avto.pro/img/mi/55054/67/01.jpeg',
        code: 'AED',
    },
    {
        title: 'Генератор Mitsubishi-Lancer',
        description: 'Генератор Mitsubishi-Lancer',
        year: '2015',
        production: 'Japan',
        price: '150',
        mileage: '39,433',
        id: 2,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8fQ65HdKp4rcFkkgBRl4iLUTh66gczL5pBxO7Z-UnuFrm_PW5RMZP4jxzSMGHki3k_s4&usqp=CAU',
        code: 'JPN',
    },
]

